// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -fsigned-char types.go

package afpacket

const VLAN_HLEN = 4

const ETH_ALEN = 0x6

type TPacketHdr struct {
	Status    uint64
	Len       uint32
	Snaplen   uint32
	Mac       uint16
	Net       uint16
	Sec       uint32
	Usec      uint32
	Pad_cgo_0 [4]byte
}

const SizeOfTPacketHdr = 0x20

type TPacket2Hdr struct {
	Status    uint32
	Len       uint32
	Snaplen   uint32
	Mac       uint16
	Net       uint16
	Sec       uint32
	Nsec      uint32
	Vlan_tci  uint16
	Vlan_tpid uint16
	Padding   [4]uint8
}

const SizeOfTPacket2Hdr = 0x20

type TPacket3Hdr struct {
	Next_offset uint32
	Sec         uint32
	Nsec        uint32
	Snaplen     uint32
	Len         uint32
	Status      uint32
	Mac         uint16
	Net         uint16
	Hv1         TPacketHdrVariant1
	Padding     [8]uint8
}

const SizeOfTPacket3Hdr = 0x30

type SockAddrLL struct {
	Family   uint16
	Protocol uint16
	Ifindex  int32
	Hatype   uint16
	Pkttype  uint8
	Halen    uint8
	Addr     [8]uint8
}

type TPacketBlockDesc struct {
	Version uint32
	To_priv uint32
	Hdr     [40]byte
}
type TPacketBdTs struct {
	Sec  uint32
	Usec uint32
}
type TPacketHdrV1 struct {
	Block_status        uint32
	Num_pkts            uint32
	Offset_to_first_pkt uint32
	Blk_len             uint32
	Seq_num             uint64
	Ts_first_pkt        TPacketBdTs
	Ts_last_pkt         TPacketBdTs
}
type TPacketHdrVariant1 struct {
	Rxhash    uint32
	Vlan_tci  uint32
	Vlan_tpid uint16
	Padding   uint16
}
